# Generated by Django 5.2.7 on 2025-10-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacarteira',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacarteira',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_carteira_excluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacarteira',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacarteira',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
