# Generated by Django 5.2.7 on 2025-10-25 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0004_alter_empresa_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('conta_criar', 'Criar conta'), ('conta_excluir', 'Excluir conta'), ('conta_restaurar', 'Restaurar conta'), ('conta_recibo', 'Visualizar recibo de conta'), ('conta_recibo_print', 'Imprimir recibo de conta'), ('pgto_registrar', 'Registrar pagamento'), ('pgto_recibo', 'Visualizar recibo de pagamento'), ('pgto_recibo_print', 'Imprimir recibo de pagamento'), ('login', 'Login'), ('logout', 'Logout'), ('outro', 'Outro')], default='outro', max_length=40)),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='carteira_au_created_6fe403_idx'), models.Index(fields=['action'], name='carteira_au_action_066d63_idx')],
            },
        ),
    ]
