# Generated by Django 5.2.7 on 2025-10-31 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
