# Generated by Django 5.2.7 on 2025-11-11 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
