# Generated by Django 5.2.7 on 2025-11-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0007_cliente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='endereco aqui', max_length=150),
        ),
    ]
