# Generated by Django 5.2.7 on 2025-11-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0008_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='email-do-cliente@mail.com.br', max_length=150),
        ),
    ]
